### ISSUE TITLE
mmd:keywords

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#12]
The current implementation more or less covers the SolR implementation. Check sub elements, in particular reference and whether that should be renamed to e.g. resource for consistency with other elements.

And modify the example to refer to the GCMD web service in stead if the web page.

**Comment by ferrighi** [comment]
I think we should change reference to resource, as we use this term in all other fields that refer to URL/URI. I will do this and change the URI to the GCMD example to https://gcmdservices.gsfc.nasa.gov/static/kms/

**Comment by steingod** [comment]
This is done through a PR now.
