### ISSUE TITLE
mmd:instrument

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#13]
This is related to WIGOS, check if harmonisation is possible, but remember that NBS requirements must be covered.

**Comment by hevgyrt** [comment]
We should add 1) SRAL (SAR ALTIMETER) for Sentinel-3 and 2) TROPOMI (TROPOspheric Monitoring Instrument) for Sentinel-5p in the Instruments section in the controlled vocabularies. 

Moreover, we should consider to add another element in MMD related to product-information, or add this to an existing. The new element could potentially contain the product_type sub-element in Instrument and also host information concerning product processing level, timeliness (NRT, etc.), orbit direction, relative orbit number, and absolute orbit number. This overlaps with [issue 41](https://github.com/steingod/mmd/issues/41).

**Comment by ferrighi** [comment]
Should we follow the OSCAR tables here, they are very handy. We find everything and can harmonize with acronyms/short and long name etc, for both instruments and platforms, e.g.:
http://www.wmo-sat.info/oscar/instruments/view/450
As far as I understood, OSCAR is fully implementing WIGOS, isn't it? Do this for all Sentinels we need to cover?

**Comment by steingod** [comment]
OSCAR is the surface component of WIGOS, the reference you have is for the space component. But we should do as you suggest, I have however not seen the machinbe actionable information for the space component yet and just asked WMO. Will have a meeting with them tomorrow on related issues as well.

**Comment by mortenwh** [comment]
I've added this as a potential task in the sprint

**Comment by ferrighi** [comment]
Instrument is now integrated as part of the platform element.
