### ISSUE TITLE
mmd:related_information

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#14]
Check controlled vocabulary.

**Comment by steingod** [comment]
Following the update of dataset_citation PR etc I am updating the controlled vocabulary for this tag to support linkages with e.g. WIGOS metadata.

**Comment by ferrighi** [comment]
I've seen you have added "Observation Facility" in the controlled vocabulary. Do you have more in mind? Or should we close this?

**Comment by steingod** [comment]
Not for now I think. Unless you have some?

**Comment by ferrighi** [comment]
I agree for now we seem to be well covered. It can always be extended if needed.
