### ISSUE TITLE
mmd:data_center

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#16]
Remove personnel information. Consider removing sub element dataset_id.

**Comment by steingod** [comment]
First part is actually implemented. Not sure if we need to look into last part yet? @ferrighi should we remove dataset_id as this is covered by DOI (in citation/reference) and metadata_identifier?

**Comment by ferrighi** [comment]
yes, it can be surely one of the alternate identifier. I will remove it and fix the documentation.
