### ISSUE TITLE
mmd:reference

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#18]
Consider replacing this by dataset_citation and potentially extension of categories in related_information in order to simplify usage. If not replaced, flatten.

**Comment by steingod** [comment]
We should check the regulations that re emerging for schema.org in this context to simplify this for future use. Furthermore the ESIP guides for citation should be implemented to generate automatic citation phrases when a publication is not available.

**Comment by steingod** [comment]
Duplicate of #17. I think that only one of these fields is required. How should we move forward on this. I think citation is a good term that is readily understood by people, but we also need to agree on the structure. Either we require a free text string according to a certain form or we require sub elements with different parts of the citation. The former is easiest for us and compliant with how others are doing this, the second more powerful, but require more work by data providers and ourselves. Any views @ferrighi in relattion to e.g. DataCite?

**Comment by ferrighi** [comment]
I think it would be better to use the structure. Then it will be much easier to extract publisher and publication_year which is what we need to pass to datacite. The citation string provided by datacite is: Creator (PublicationYear): Title. Publisher. (resourceTypeGeneral). Identifier.

**Comment by steingod** [comment]
But do you think people will provide us with this? And what we harvest normally doesn't support this. We could however extract and create the structure although it can be complicated. Any idea on how to do that, preferably in XSLT, if necessary in a Python setup?

**Comment by steingod** [comment]
Do we agree on the following:

1. Merging reference and dataset_citation, only continuing with one?
2. If so, what is the preferred tag to continue? dataset_citation?
3. Do we go for the structured approach? When we decide I will update XSLTs and test.

**Comment by ferrighi** [comment]
Yes to all of them. I think at the end, having the structured approach guides the provider to make a good citation. We need to extract publisher and publication years. And it will be much easier with the structured approach.

**Comment by steingod** [comment]
I will prepare a PR for this and assign to you for review. I will use elements from reference as dataset_citation more or less duplicates information already available in the MMD specification which really doesn't make sense...
