### ISSUE TITLE
Controlled vocabulary Platform

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#20]
Check consistency with Activity Type vocabulary as well as upper/lower case implementation.

**Comment by ferrighi** [comment]
The upper/lower case is fixed now in to PR #64. 
Could you specify what you refer to with consistency with Activity vocabulary? 
Additionally there is a vocabulary in the thesauri folder, which is called mmd_platform, but it is just a copy of the activity_type file. I guess for now we just point to wmo resources for the satellite platforms, so we don't need an internal vocabulary.

**Comment by ferrighi** [comment]
Is there something more to do for this issue or should we close it?

**Comment by steingod** [comment]
Sorry, this has passed my attention. I was thinking whether we should adopt some existing or emerging vocabulary (e.g. through GCMD, WIGOS or other). To my knowledge there is no good alternatives yet (GCMD is inconsistent, WIGOS is too narrow) so I suggest to close for now.

**Comment by ferrighi** [comment]
Yes. We'll keep an eye on this for the future. I'll close it for now then.
