### ISSUE TITLE
metadata identifier for datacite xsl

### ISSUE THREAD

**Issue by ferrighi** [steingod/mmd#22]
The identifier property in datacite mandatory fields is only a DOI. 
The attribute identifierType value allowed from the controlled vocabulary is "DOI" (https://schema.datacite.org/meta/kernel-4.3/doc/DataCite-MetadataKernel_v4.3.pdf), so we cannot map it to the metadata_identifier. 

<xsl:template match="mmd:metadata_identifier">
	<xsl:element name="identifier">
		<xsl:value-of select="." />
	</xsl:element>
</xsl:template>

**Comment by steingod** [comment]
Will you modify the XSLT?

**Comment by ferrighi** [comment]
Yes, I'll work on it.

**Comment by steingod** [comment]
Time to close this?
