### ISSUE TITLE
Documentation and examples should be added to README

### ISSUE THREAD

**Issue by mortenwh** [steingod/mmd#25]
The functionality of content in the different folders should be explained, possibly with short examples of the usage.

**Comment by mortenwh** [comment]
I also checked if asciidoc can be used with readthedocs, and it is not possible (or at least the team behind readthedocs is not willing to implement it - see https://github.com/readthedocs/readthedocs.org/issues/2702). It would, however, be very useful to have an autogenerated website for the documentation. Is this possible to have this for asciidoc without a lot of work? How do others handle that?

Readthedocs is a very common documentation site that integrates well with GitHub and is familiar to many people. I can't find the discussions we had earlier in slack, but would it be an idea to reconsider it? What was the reason to select asciidoc?

**Comment by steingod** [comment]
I have never used it but Antora can be an option for documenting source code. However, there are also major differences between documenting code and creating guidance documentation. Asciidoc is the same solution as CF is using for the CF conventions and integrates also very well with GitHub. We should not add more host services than we have. I know readthedocs is a hosted service (outside GitHub??) but that local services can be established as well. I have however so far not seen any major guidance documentation created in readthedocs, only software documentation. I may be wrong however.

Concerning autogenerated documents using Asciidoc this is already in use by CF. It is not a major task to set some update in either GitHub  or in relation to our own web servers.

**Comment by ferrighi** [comment]
@magnarem has been adding some documentation concerning the src directory, describing each file and adding how to run it. I will close this issue and we can open more specific issues if more documentation is needed.
