### ISSUE TITLE
SPDX licence list

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#31]
Consider to implement SPDX license list for usage with use and access constraints elements. Elements of the discussion on schema.org through ESIP at https://github.com/ESIPFed/science-on-schema.org/issues/47#issuecomment-572626877 could be useful to follow in this context. Furthermore, SPDX maintain machine readable forms of the licenses at https://github.com/spdx/license-list-data.

@ferrighi, @mortenwh, @epifanio and @hevgyrt what do you think?

**Comment by ferrighi** [comment]
I think we should definitely do this. Do we just translate the use_constraints.xml controlled vocabulary or are you looking for a longer list? For now we have: 
public->CC0
Attribute->CC BY
Share-alike-> CC BY-SA
Non commercial-> CC BY-NC
No derivative-> CC BY-NC-ND
(sounds plenty to me). 
We could create a new skos vocabulary.

**Comment by steingod** [comment]
I agree that these are the most likely ones we need now. I would rather start with something like this and then amend later if necessary. I would also suggest that we either

1. change the use_constraint to hold a canonical URL (SPDX)
2. change the use_constraint to hold both a canonical URL and a text (suggesting to use SPDX identifier).

This translates into statements like
`
<use_constraint>
  <identifier>CC-BY-4.0</identifier>
  <resource>https://spdx.org/licenses/CC-BY-4.0</resource>
</use_constraint>
`
I would also suggest that we in documentation say we shouid use the SPDX identifier. Having a SKOS representation that supports this also means that we can enrich harvested metadata during harvest.

**Comment by ferrighi** [comment]
As far as I can understand both DIF and ISO just give a string as entry here. I was planning to modify also the xslt, but it might be that there is no real translation. What do you usually do in this case?

**Comment by steingod** [comment]
If there is no translation there is no then  we only translate the text. For ISO you have the codelist element which could be used, in DIF not. I will check both better, but neither should prevent us from having more detailed information.

**Comment by ferrighi** [comment]
Should we close this for now? The PR for this issue has been merged. 

Here again, to improve, we should use at some point the skos vocabulary provided to validate the schema and not just a list in mmd.xsd. 
With respect to what you write above, i.e. translate text, I don't see we have space for it, we only have identifier and resource. First is a controlled vocabulary.

**Comment by steingod** [comment]
The identifier is a text that can be translated when moving into other information domains (e.g. GCMD DIF). I didn't mean more than that. And agree.
