### ISSUE TITLE
Add relevant platform and instruments

### ISSUE THREAD

**Issue by TAlonglong** [steingod/mmd#32]
In platform and instrument add relevant platform and instruments.

eg. NOAA-20, VIIRS
The platform long names should use the WMO OSCAR acronym naming as a guide line eg https://www.wmo-sat.info/oscar/satellites/view/208
For the sensor(instrument) this will be the short name

**Comment by steingod** [comment]
Do you know if this will be added in machine readable form (needed for integration) to https://codes.wmo.int/wmdr and the WMDS section there? Surface vocabularies are added, but I haven't seen any from the satellite component of WIGOS yet.

**Comment by steingod** [comment]
I have been discussing this with WMO the last days, waiting for feedback now. Currently there are no plans AFAIK to make this machine readable, but the issue has now been raised and I wait for response. The idea is to use this in the context of #41 using references only.

**Comment by ferrighi** [comment]
Looking towards extending mmd to more data at MET, we need:

Platforms: Metop-A, Metop-B, Metop-C, NOAA-18, NOAA-19, NOAA-20, SUOMI NPP, FENGYUN-3D ( soon also FENGYUN-3E), AQUA and TERRA. 

Instruments, VIIRS, AVHRR, MERSI-2, and MODIS

This can be added in a new working branch after the already planned release.

**Comment by ferrighi** [comment]
@TAlonglong , do you need AVHRR, AVHRR/2 and AVHRR/3?

**Comment by TAlonglong** [comment]
Yes, good point. I keep forgetting there are several versions. I will only use AVHRR/3 https://www.wmo-sat.info/oscar/instruments/view/62 but it will be good to add the two others.
