### ISSUE TITLE
Modification to mmd:identifier?

### ISSUE THREAD

**Issue by steingod** [steingod/mmd#40]
There is a need to support multiple identifiers as well as potentially extending the MET UUID to contain a namespace (no:met:) as well. The current specification of this element is e.g.:

`<metadata_identifier>
9663fc67-5687-4bf2-a274-f3826e41fdc8
</metadata_identifier>
`
Potential new structure could be:
'
<metadata_identifier>
  <identifier>9663fc67-5687-4bf2-a274-f3826e41fdc8</identifier>
  <doi>DOI here</doi>
  <wmo></wmo>
</metadata_identifier>
'
Finally it is suggested to extend the current UUID identifier to include namespace in the form no:met:<UUID>. This is potentially in conflict with the DIF implementation. Other separators could be used, and details on DIF should be checked carefully.

**Comment by ferrighi** [comment]
How about using attributes here like: 
<identifiers>
  <identifier id_type="MET UUID">xxx3826e41fdc8</identfifier> 
  <identifier id_type="DOI">doi-here</identifier>
<identifiers>

or use even separate entries: 
<metadata_identifier>xxx3826e41fdc8</metadata_identfifier> 
<alternate_identifier aid_type="DOI">doi-here</alternate_identfifier>

**Comment by steingod** [comment]
Wouldn't it be better to keep DOI in the citation section? I see that we could need more identifiers at some point, but then I am more thinking of WIS identifiers etc (also potentially MET identifiers for stations which shold be linked with WIGOS identifies, but those are for stations, not the data). For DOI I think I would prefer the citation element, then we just add that when it gets published.

**Comment by ferrighi** [comment]
yes, sure DOI can stay in the citation element. It was just an example since you have mentioned it in the issue, but the attribute type could be "WIS id". So if we need to support more than one identifier would you have multiple elements or several entries of the same element?

**Comment by steingod** [comment]
I have no preference in this context. What is your perspective?

**Comment by ferrighi** [comment]
I say it is just less work to keep "metadata_identifier" as it is, and just add all other IDs to an "alternate_identifier" with attributes.

**Comment by steingod** [comment]
Agree. Will look into a PR on this.

**Comment by ferrighi** [comment]
Remember that the dif element "dif:Data_Set_ID" should translate into alternate_identifier when you update xslt files, as we have removed dataset_id according to #16

**Comment by mpejcoch** [comment]
@steingod can Lara take this issue and do it as part of S-ENDA or have you already started?

**Comment by steingod** [comment]
A PR is created #61.
