### ISSUE TITLE
temporal_extent

### ISSUE THREAD

**Issue by ferrighi** [steingod/mmd#43]
Temporal extent is now defined in the doc as just a date string, but it should point to a date+time string. 

<mmd:start_date>2014-02-01</mmd:start_date>
should be: 
<mmd:start_date>2014-02-01T12:00:00Z</mmd:start_date>

Then schema should accordingly change from type="xs:date" to type="xs:dateTime"

I could dare doing this if ok with you, just reassign.

**Comment by steingod** [comment]
Yes please do.

**Comment by steingod** [comment]
I think this is already done by the PR by Bard that I approved. Could you double check and close if done?

**Comment by ferrighi** [comment]
Bard PR was just the change of the schema from time to datetime. We need to change the documentation, and the xslt files. I have prepared a branch for this. I just need to revise and PR.

**Comment by steingod** [comment]
I checked your PR, looks good. Just need to resolve PDF conflict.
