### ISSUE TITLE
fixes for platform releted elements

### ISSUE THREAD

**Issue by ferrighi** [steingod/mmd#69]
A few "minor" things to be fixed for consistency in the documentation: 

1) polarization example in doc:
<mmd:polarisation>VV VH</mmd:polarisation>
polarization code list in doc:
VV+VH
According to the wmo resource the correct is with a "+".  I will add the "+"

2) long name in doc: 
Synthetic Aperture Radar (C-band) 
long name in code list: 
Synthetic Aperture Radar C-band
I will add the parenthesis as in wmo. 

3) from MSI, the instrument for S2 is called "Multi-Spectral Imager for Sentinel-2", suggesting there is something specific for this instrument on S2, then just a generic MSI. I can fix this as well. 

4) in xsd resource: 
<xs:element name="resource" type="xs:string" maxOccurs="0" minOccurs="1"></xs:element>
should be maxOccurs="1"

I'll proceed if it is ok.

**Comment by steingod** [comment]
Yes please do so.
