### ISSUE TITLE
In platform orbit_direction is mandatory, but not instrument. Is this the intention?

### ISSUE THREAD

**Issue by TAlonglong** [steingod/mmd#77]
Looking at the xsd/mmd.xsd here
https://github.com/steingod/mmd/blob/master/xsd/mmd.xsd#L254-L255

I see the orbit_direction has `minOccurs` set to, but intrument has `minOccurs` set to 0. Is this the intention?

**Comment by ferrighi** [comment]
I have noticed that indeed. The fix is contained in the PR #75
